## Практическое задание

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

> <img src="lesson3.1.png">
>
> Получаются вектора
> $$\begin{pmatrix}
2 \\ 
-1 
\end{pmatrix} \begin{pmatrix}
3 \\ 
-2 
\end{pmatrix}$$

In [6]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

> <img src="lesson3.2.png">

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

> Да является потому что можно найти Lambda
>
> <img src="lesson3.3.png">

In [4]:
a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Собственные значения:
[2. 2.]
Собственные векторы:
[[ 0.71 -0.71]
 [ 0.71 -0.71]]


__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

> НЕТ не является потому что нельзя найти Lambda
>
> <img src="lesson3.4.png">

In [5]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(a)
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.71 -0.71  0.  ]
 [ 0.71  0.71  0.  ]
 [ 0.    0.    1.  ]]
