In [2]:
import numpy as np

## Практическое №1

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
        
> нельзя перемножить потому что необходимо чтобы число столбцов матрицы 𝐴 было равно числу строк матрицы 𝐵.
        
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
        
> можно перемножить только A * B потому что число столбцов матрицы 𝐴 равно числу строк матрицы 𝐵. Размерность в данном случае будет 2x3
        
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
        
> можно перемножить A * B и B * A так как выпоняется нужное условие столбцов и строк
> A * B размерность будет 3x3
> B * A размерность будет 8x8
        
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
        
> можно перемножить A * B и B * A так как выпоняется нужное условие столбцов и строк. Размерность в обоих случаях будет 4x4
        
    
__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

<img src="lesson1.2.png">

In [20]:
a = np.array([[1, -2],[3,0]])
b = np.array([[4, -1],[0,5]])
print('Сложение\n', a + b)
print('Умножение\n', a @ b)

Сложение
 [[ 5 -3]
 [ 3  5]]
Умножение
 [[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$


<img src="lesson1.3.png">

In [24]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])

3*a - 2*b + 4*c

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

<img src="lesson1.4.png">

In [31]:
a = np.array([[4, 1], [5, -2], [2, 3]])

print('A * At =\n', a @ a.T)
print('At * A =\n', a.T @ a)

A * At =
 [[17 18 11]
 [18 29  4]
 [11  4 13]]
At * A =
 [[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [58]:
!!! work in progress !!!

# def shape(a):
#     m = len(a)
#     n = len(a[0])
#     for i in a:
#         if len(i) != n:
#             raise NameError('Different dimension in arrays')
#     return (m, n)

# def dot(a, b):
#     m, n = shape(a)
#     n1, k = shape(b)
    
#     print(m, n)
#     print(n1, k)
#     if n != n1:
#         raise NameError(f'Shapes ({m}, {n}) and ({n1}, {k}) not aligned')

#     c = []
#     for i in range(n):
#         for p in range(k):
#             print(a[i][j])
            
        
    

# a = np.array([[1,2],[1,2],[1,2]])
# b = np.array([[3,4,5,6], [3,4,5,6]])
# # np.dot(a, b)

# dot(a, b)

['zsh:1: command not found: work']

## Практическое №2

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    

   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$