In [1]:
import numpy as np

## Практическое №1

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
        
> нельзя перемножить потому что необходимо чтобы число столбцов матрицы 𝐴 было равно числу строк матрицы 𝐵.
        
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
        
> можно перемножить только A * B потому что число столбцов матрицы 𝐴 равно числу строк матрицы 𝐵. Размерность в данном случае будет 2x3
        
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
        
> можно перемножить A * B и B * A так как выпоняется нужное условие столбцов и строк
> A * B размерность будет 3x3
> B * A размерность будет 8x8
        
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
        
> можно перемножить A * B и B * A так как выпоняется нужное условие столбцов и строк. Размерность в обоих случаях будет 4x4
        
    
__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

<img src="lesson1.2.png">

In [2]:
a = np.array([[1, -2],[3,0]])
b = np.array([[4, -1],[0,5]])
print('Сложение\n', a + b)
print('Умножение\n', a @ b)

Сложение
 [[ 5 -3]
 [ 3  5]]
Умножение
 [[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$


<img src="lesson1.3.png">

In [3]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])

3*a - 2*b + 4*c

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

<img src="lesson1.4.png">

In [4]:
a = np.array([[4, 1], [5, -2], [2, 3]])

print('A * At =\n', a @ a.T)
print('At * A =\n', a.T @ a)

A * At =
 [[17 18 11]
 [18 29  4]
 [11  4 13]]
At * A =
 [[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [5]:
def shape(a):
    m = len(a)
    n = len(a[0])
    for i in a:
        if len(i) != n:
            raise NameError('Different dimension in arrays')
    return (m, n)

def dot(a, b):
    m, n = shape(a)
    n1, k = shape(b)

    if n != n1:
        raise NameError(f'Shapes ({m}, {n}) and ({n1}, {k}) not aligned')

    res = []
    for i in range(m):
        row = []
        for p in range(k):
            sm = 0
            for j in range(n):
                sm += a[i][j] * b[j][p]
            row.append(sm)
        res.append(row)
    return res
        
    

a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[7,8,9,10], [11,12,13,14]])

c = dot(a, b)
correct = np.dot(a, b)

print('Результат:\n', c)
print('Проверка правильности функции:\n', correct == c)

Результат:
 [[29, 32, 35, 38], [65, 72, 79, 86], [101, 112, 123, 134]]
Проверка правильности функции:
 [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


## Практическое №2

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

> $$sin(x)*sin(x) - (-cos(x)*cos(x)) = sin^2(x)+cos^2(x) = 1$$

In [6]:
from math import sin, cos
x = 10
a = np.array([[sin(x), -cos(x)], [cos(x), sin(x)]])
np.linalg.det(a)

1.0

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    

> согласно свойству №7 определителей так как матрица треугольная то определитель будет равен произведению по диагонали
>
> $$ 4 * 5 * 9 = 180$$

In [7]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(a)

180.0

   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

> разложим определитель по первой строке
> $$(-1)^{1+1} * 1 * \begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix} + (-1)^{1+2} * 2 * \begin{vmatrix}
4 & 6\\ 
5 & 9
\end{vmatrix} + (-1)^{1+3} * 3 * \begin{vmatrix}
4 & 5\\ 
7 & 8
\end{vmatrix} = $$
>
> $$ = 1*(5*9-8*6) - 2*(4*9-7*6) + 3*(4*8-7*5) = 0$$

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'{np.linalg.det(a):.0f}')

-0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;

> будет равен 4 * 4 = 16 согласно свойству определителей №9
> $$det(A * A)=detA\cdot detA.$$
    
   б) $det(A^{T})$;
   
> будет равен 4 согласно свойству определителей №1    
    
   в) $det(2A)$.
   
> Если квадратная матрица n-того порядка умножается на некоторое ненулевое число, то определитель полученной матрицы равен произведению определителя исходной матрицы на это число в n-той степени:
> $$ B = k·A => det(B) = k^n * det(A)$$
> 
> Итого определитель будет равен $$2^n * 4$$ и будет зависитель от порядка матрицы

In [9]:
a = np.array([[1, 2, 3], [1, 2, 1], [2, 3, 4]])
n = np.linalg.matrix_rank(a)
d = np.linalg.det(a)

print(f'Пусть дана матрица A =\n{a}\n{n}-го порядка и ее определитель равен = {d}\nтогда det(2*A) = {pow(2,3) * d}\n')
print(f'Проверяем через питон = {np.linalg.det(2*a):.0f}')

Пусть дана матрица A =
[[1 2 3]
 [1 2 1]
 [2 3 4]]
3-го порядка и ее определитель равен = -2.0
тогда det(2*A) = -16.0

Проверяем через питон = -16


__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

> Матрица называется сингулярной, или вырожденной, если ее определитель равен нулю.

In [10]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
d = np.linalg.det(a)

if d == 0:
    print('Так как определитель матрицы = 0 данная матрица является вырожденной')
else:
    print('Матрица является НЕвырожденной')

Так как определитель матрицы = 0 данная матрица является вырожденной


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

> 3тья строка является суммой 1ой и 2ой значит ее отбрасываем
>
> $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$
>
> больше преобразований сделать не получиться поэтому ранг матрицы равен 2

In [11]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
np.linalg.matrix_rank(a)

2

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

> 3тья строка является суммой 1ой и 2ой значит ее отбрасываем
>
> $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$
>
> больше преобразований сделать не получиться поэтому ранг матрицы равен 3

In [12]:
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(a)

3