In [1]:
import numpy as np

## Практическое задание №1

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

> <img src="lesson4.1.jpg">

In [2]:
M = np.array([[1, 1, -1], [2, 1, -1], [1, 1, -3]]) 
v = np.array([0, -2, 4]) 
# для x4 = 0
np.linalg.solve(M, v)

array([-2.,  0., -2.])

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    

>  система совместна и имеет единственное решение потому что здесь число уравнений равно числу неизвестных и матрица коэффициентов невырождена, все векторы столбцов коэффициентов линейно независимы

In [3]:
M = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]]) 
v = np.array([4, -17, 0]) 

np.linalg.solve(M, v)

array([1., 2., 3.])

   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    

> <img src="lesson4.2.png">

   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

>  система совместна и имеет множество решений потому что здесь число уравнений НЕ равно числу неизвестных а все векторы столбцов коэффициентов линейно независимы

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [4]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]]) 
b = np.array([3, 2, 4, 1]) 

rankA = np.linalg.matrix_rank(A)

A_ = np.hstack((A, b.reshape(4, 1)))
rankA_ = np.linalg.matrix_rank(A_)

if rankA == rankA_:

    if rankA == 4: # 4 - число неизвестных
        print('Cистема определена, т.е. имеет единственное решение', np.linalg.solve(A, b))
    elif rankA < 4:
        print('Cистема совместна и имеет бесконечное количество решений')
else:
    print('Cистема НЕ совместна')


Cистема определена, т.е. имеет единственное решение [2.76666667 0.3        1.33333333 0.5       ]


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

> <img src="lesson4.3.png">

## Практическое задание №2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    

> <img src="lesson4.4.png">

In [5]:
M = np.array([[1, -2], [3, -4]]) 
v = np.array([1, 7]) 

np.linalg.solve(M, v)

array([5., 2.])

   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

> <img src="lesson4.5.png">

In [6]:
M = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]]) 
v = np.array([10, -2, 1]) 

np.linalg.solve(M, v)

array([ 2., -1.,  1.])

__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    

> <img src="lesson4.6.png">

   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    

> <img src="lesson4.7.png">

__3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

> <img src="lesson4.8.png">

In [7]:
M = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]]) 
v = np.array([1, -6, -5]) 

np.linalg.solve(M, v)

array([-1.00000000e+00,  2.44249065e-16,  1.00000000e+00])

__4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

> <img src="lesson4.9.png">

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [8]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]]) 
b = np.array([1, -6, -5]) 

def matrix(C, t):
    t = np.array([[t[i]] for i in range(len(t))], float)
    C[1:,:] = C[1:,:] - t*C[0,:]
    return C

def solve(A, b):
    lu = np.array(A, float)
    for k  in range(lu.shape[0]-1):
        t = lu[k:, k][1:] / lu[k:, k][0]
        lu[k+1:,k] = t
        lu[k:, k+1:] = matrix(lu[k:, k+1:], t)

    b = np.array(b,float)
    for i in range(1,len(b)):
        b[i] = b[i] - np.dot(lu[i,:i],b[:i])
    for i in range(len(b)-1, -1, -1):
        b[i] = (b[i] - np.dot(lu[i,i+1:],b[i+1:]))/lu[i,i]
    return b

solve(A, b)

array([-24.6, -11.2,  12. ])