In [2]:
import numpy as np

## Практическое задание №1

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

> <img src="lesson4.1.png">

In [15]:
M = np.array([[1, 1, -1], [2, 1, -1], [1, 1, -3]]) 
v = np.array([0, -2, 4]) 

np.linalg.solve(M, v)

array([-2.,  0., -2.])

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    

> <img src="lesson4.1.png">

In [6]:
M = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]]) 
v = np.array([4, -17, 0]) 

np.linalg.solve(M, v)

array([1., 2., 3.])

   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    

> <img src="lesson4.1.png">

In [7]:
M = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]]) 
v = np.array([1, -2, 5]) 

np.linalg.solve(M, v)

LinAlgError: Singular matrix

   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

> <img src="lesson4.1.png">

In [ ]:
M = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]]) 
v = np.array([4, -17, 0]) 

np.linalg.solve(M, v)

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

> <img src="lesson4.1.png">

In [8]:
M = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]]) 
v = np.array([3, 2, 4, 1]) 

np.linalg.solve(M, v)

array([2.76666667, 0.3       , 1.33333333, 0.5       ])

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

> <img src="lesson4.1.png">

## Практическое задание №2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    

> <img src="lesson4.1.png">

In [9]:
M = np.array([[1, -2], [3, -4]]) 
v = np.array([1, 7]) 

np.linalg.solve(M, v)

array([5., 2.])

   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

> <img src="lesson4.1.png">

In [10]:
M = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]]) 
v = np.array([10, -2, 1]) 

np.linalg.solve(M, v)

array([ 2., -1.,  1.])

__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    

> <img src="lesson4.1.png">

   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    

> <img src="lesson4.1.png">

__3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

> <img src="lesson4.1.png">

__4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

> <img src="lesson4.1.png">

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.